FROM maven:3.8.1-openjdk-17 AS MAVEN

MAINTAINER BOTTOMHALF-STAGING

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn package

FROM openjdk:17-oracle
WORKDIR /app
EXPOSE 8090

COPY --from=MAVEN /build/target/hiringbel_apigateway.jar /app/

ENTRYPOINT ["java", "-jar", "hiringbel_apigateway.jar", "--spring.profiles.active=staging"]